"""PowerPoint COM automation: insert per-slide audio.

Scope (current milestone):
- Insert the MP3 generated by ``tts.generate_audio_files`` into its matching slide.
- Shrink the inserted audio icon and tuck it into the top-right corner
  (instead of leaving it full-size and top-left, which is PowerPoint's
  default and quite intrusive), and set it to hide while not playing.
- Slides without a matching audio file are left completely untouched
  (no timing changes, no forced auto-advance).

Note on "auto-play" vs "on click": the animation *timeline's* click/auto
trigger (what the PowerPoint UI shows under Audio Tools > Playback > Start)
has no effect on PowerPoint's video export - this module does not attempt to
change it (an earlier attempt to do so via the slide's animation timeline
turned out to be unreliable across PowerPoint COM versions anyway). However,
the legacy ``AnimationSettings.PlaySettings.PlayOnEntry`` flag DOES matter
for export even though it has no visible effect in the editor UI: leaving it
unset was empirically found to make PowerPoint's "Create a Video" export
ignore the embedded audio entirely and fall back to a fixed 5-second slide
duration with no sound. So ``PlayOnEntry`` is set alongside
``HideWhileNotPlaying`` even though the UI keeps showing "On Click".

Explicitly OUT of scope for this milestone:
- Automatic slide advance / transition timing (PowerPoint's video export
  already sizes each slide's duration to its embedded audio automatically).
- MP4 export itself (the next step, once audio insertion is verified).

This module requires Windows with Microsoft PowerPoint and pywin32 installed,
since it drives PowerPoint over COM. It cannot be exercised on non-Windows
systems; ``_require_windows`` raises a clear error instead of failing with a
confusing import error.
"""

import sys
from pathlib import Path
from typing import Any, Dict, List, Optional


# Icon size and margin (in points) used to shrink the inserted audio icon
# and tuck it into a corner instead of leaving it at full size top-left.
ICON_SIZE_PT = 10
ICON_MARGIN_PT = 10


def _require_windows() -> None:
    if sys.platform != "win32":
        raise RuntimeError(
            "PowerPoint automation requires Windows with Microsoft PowerPoint "
            "and pywin32 installed. This step cannot run on this platform."
        )


def load_audio_manifest(manifest_path: Path | str) -> Dict[str, Any]:
    """Load the manifest.json produced by tts.generate_audio_files."""
    import json

    manifest_path = Path(manifest_path)
    if not manifest_path.exists():
        raise FileNotFoundError(f"Audio manifest not found: {manifest_path}")
    with manifest_path.open("r", encoding="utf-8") as f:
        return json.load(f)


def _build_slide_audio_map(manifest: Dict[str, Any], audio_dir: Path) -> Dict[int, Path]:
    slide_audio_map: Dict[int, Path] = {}
    for entry in manifest.get("slides", []):
        audio_file = entry.get("audio_file")
        if not audio_file:
            continue
        slide_num = int(entry["slide_num"])
        slide_audio_map[slide_num] = audio_dir / audio_file
    return slide_audio_map


def insert_audio(
    pptx_path: Path | str,
    manifest: Dict[str, Any],
    audio_dir: Path | str,
    output_path: Optional[Path | str] = None,
    visible: bool = True,
    powerpoint_app: Optional[Any] = None,
) -> Dict[str, Any]:
    """Insert each slide's audio file into its matching slide.

    Args:
        pptx_path: Path to the source .pptx file.
        manifest: The audio manifest dict (as produced by
            ``tts.generate_audio_files`` / saved as manifest.json), mapping
            slide numbers to audio file names.
        audio_dir: Directory containing the MP3 files referenced by the
            manifest (the manifest only stores file names, not full paths).
        output_path: Where to save the resulting .pptx. Defaults to
            overwriting ``pptx_path``.
        visible: Whether the PowerPoint window should be shown while working.
            PowerPoint's COM automation is more reliable with the window
            visible; kept as a parameter so it can be hidden once the flow
            is proven stable.
        powerpoint_app: Optional pre-existing PowerPoint COM Application
            object. Mainly used for testing (inject a fake) or to reuse an
            already-running instance instead of starting a new one.

    Returns:
        A summary dict: ``{"output_path", "inserted_slides", "skipped_slides"}``.

    Slides without a matching audio file are left untouched entirely -
    no shapes are added and no slide settings are changed.
    """
    _require_windows()

    pptx_path = Path(pptx_path).resolve()
    audio_dir = Path(audio_dir).resolve()
    output_path = Path(output_path).resolve() if output_path else pptx_path

    if not pptx_path.exists():
        raise FileNotFoundError(f"PPTX file not found: {pptx_path}")

    slide_audio_map = _build_slide_audio_map(manifest, audio_dir)

    app = powerpoint_app
    created_app = False
    presentation = None

    try:
        if app is None:
            import win32com.client  # Imported lazily: only available on Windows

            app = win32com.client.Dispatch("PowerPoint.Application")
            created_app = True
            # PowerPoint's COM automation generally requires Visible = True
            # to reliably manipulate shapes; some operations fail silently
            # with a hidden application window.
            app.Visible = True

        presentation = app.Presentations.Open(
            str(pptx_path),
            WithWindow=visible,
        )

        inserted: List[int] = []
        skipped: List[Dict[str, Any]] = []

        # Compute a top-right position for the (shrunk) audio icon so it
        # stays out of the way of slide content, without moving it off the
        # visible slide area (the deck may be reused/edited standalone).
        slide_width = presentation.PageSetup.SlideWidth
        icon_left = slide_width - ICON_SIZE_PT - ICON_MARGIN_PT
        icon_top = ICON_MARGIN_PT

        for slide_num, audio_path in slide_audio_map.items():
            if not audio_path.exists():
                skipped.append(
                    {"slide_num": slide_num, "reason": f"audio file not found: {audio_path}"}
                )
                continue

            try:
                slide = presentation.Slides(slide_num)
            except Exception as exc:  # noqa: BLE001 - surface as a skip, not a crash
                skipped.append({"slide_num": slide_num, "reason": f"slide not found: {exc}"})
                continue

            try:
                shape = slide.Shapes.AddMediaObject2(
                    FileName=str(audio_path),
                    LinkToFile=False,
                    SaveWithDocument=True,
                    Left=icon_left,
                    Top=icon_top,
                    Width=ICON_SIZE_PT,
                    Height=ICON_SIZE_PT,
                )
            except Exception as exc:  # noqa: BLE001
                skipped.append(
                    {"slide_num": slide_num, "reason": f"failed to insert audio: {exc}"}
                )
                continue

            # Best-effort: hide the icon except while it's actually playing,
            # and mark it to play on entry. NOTE: empirically, PlayOnEntry
            # is NOT just cosmetic - even though it doesn't change what the
            # editor UI shows (still "On Click"), leaving it unset caused
            # PowerPoint's "Create a Video" export to ignore the audio
            # entirely and fall back to a fixed 5-second slide duration with
            # no sound. Keep both flags set together.
            try:
                shape.AnimationSettings.PlaySettings.PlayOnEntry = True
                shape.AnimationSettings.PlaySettings.HideWhileNotPlaying = True
            except Exception:  # noqa: BLE001
                pass

            inserted.append(slide_num)

        presentation.SaveAs(str(output_path))

        return {
            "output_path": str(output_path),
            "inserted_slides": inserted,
            "skipped_slides": skipped,
        }
    finally:
        if presentation is not None:
            try:
                presentation.Close()
            except Exception:  # noqa: BLE001 - best-effort cleanup
                pass
        if created_app and app is not None:
            try:
                app.Quit()
            except Exception:  # noqa: BLE001 - best-effort cleanup
                pass
