"""PowerPoint COM automation: insert per-slide audio, export MP4.

Scope (current milestone):
- Insert the MP3 generated by ``tts.generate_audio_files`` into its matching slide.
- Shrink the inserted audio icon and tuck it into the top-right corner
  (instead of leaving it full-size and top-left, which is PowerPoint's
  default and quite intrusive), and set it to hide while not playing.
- Slides without a matching audio file are left completely untouched
  (no timing changes, no forced auto-advance).
- Export the presentation to MP4 via ``Presentation.CreateVideo()``, polling
  its asynchronous status until done (or failed/timed out).

Note on "auto-play" vs "on click": the animation *timeline's* click/auto
trigger (what the PowerPoint UI shows under Audio Tools > Playback > Start)
has no effect on PowerPoint's video export - this module does not attempt to
change it (an earlier attempt to do so via the slide's animation timeline
turned out to be unreliable across PowerPoint COM versions anyway). However,
the legacy ``AnimationSettings.PlaySettings.PlayOnEntry`` flag DOES matter
for export even though it has no visible effect in the editor UI: leaving it
unset was empirically found to make PowerPoint's "Create a Video" export
ignore the embedded audio entirely and fall back to a fixed 5-second slide
duration with no sound. So ``PlayOnEntry`` is set alongside
``HideWhileNotPlaying`` even though the UI keeps showing "On Click".

Explicitly OUT of scope for this milestone:
- Automatic slide advance / transition timing (PowerPoint's video export
  already sizes each slide's duration to its embedded audio automatically).

This module requires Windows with Microsoft PowerPoint and pywin32 installed,
since it drives PowerPoint over COM. It cannot be exercised on non-Windows
systems; ``_require_windows`` raises a clear error instead of failing with a
confusing import error.

``insert_audio`` and ``export_video`` both need to open PowerPoint, open a
presentation, do their work, and reliably close both afterward - even if
something fails partway through. That open/close bookkeeping (and now, the
exception wrapping around it) is shared via the ``_powerpoint_session`` and
``_open_presentation`` context managers below, instead of being duplicated
in each function.
"""

import sys
import time
from contextlib import contextmanager
from pathlib import Path
from typing import Any, Callable, Dict, Iterator, List, Optional, Tuple

from src.exceptions import (
    AudioInsertionError,
    PowerPointLaunchError,
    VideoExportError,
    VideoExportTimeoutError,
)


# Icon size and margin (in points) used to shrink the inserted audio icon
# and tuck it into a corner instead of leaving it at full size top-left.
ICON_SIZE_PT = 10
ICON_MARGIN_PT = 10


def _require_windows() -> None:
    if sys.platform != "win32":
        raise PowerPointLaunchError(
            "PowerPoint automation requires Windows with Microsoft PowerPoint "
            "and pywin32 installed. This step cannot run on this platform."
        )


@contextmanager
def _powerpoint_session(
    powerpoint_app: Optional[Any], visible: bool
) -> Iterator[Tuple[Any, bool]]:
    """Get a PowerPoint COM Application, and ensure it's cleaned up after.

    If ``powerpoint_app`` is given (typically a real already-running
    instance, or a fake for testing), it's used as-is and left running when
    this context exits - only Applications *created* here get Quit(). Yields
    ``(app, created_app)``.
    """
    app = powerpoint_app
    created_app = False
    try:
        if app is None:
            try:
                import win32com.client  # Imported lazily: only available on Windows

                app = win32com.client.Dispatch("PowerPoint.Application")
            except Exception as exc:
                raise PowerPointLaunchError(
                    f"Failed to start PowerPoint via COM: {exc}"
                ) from exc
            created_app = True
            # PowerPoint's COM automation generally requires Visible = True
            # to reliably manipulate shapes; some operations fail silently
            # with a hidden application window.
            app.Visible = True

        yield app, created_app
    finally:
        if created_app and app is not None:
            try:
                app.Quit()
            except Exception:  # noqa: BLE001 - best-effort cleanup
                pass


@contextmanager
def _open_presentation(app: Any, pptx_path: Path, visible: bool) -> Iterator[Any]:
    """Open a presentation for ``app``, and ensure it's closed after."""
    try:
        presentation = app.Presentations.Open(str(pptx_path), WithWindow=visible)
    except Exception as exc:
        raise PowerPointLaunchError(
            f"Failed to open presentation {pptx_path}: {exc}"
        ) from exc

    try:
        yield presentation
    finally:
        try:
            presentation.Close()
        except Exception:  # noqa: BLE001 - best-effort cleanup
            pass


def load_audio_manifest(manifest_path: Path | str) -> Dict[str, Any]:
    """Load the manifest.json produced by tts.generate_audio_files."""
    import json

    manifest_path = Path(manifest_path)
    if not manifest_path.exists():
        raise FileNotFoundError(f"Audio manifest not found: {manifest_path}")
    with manifest_path.open("r", encoding="utf-8") as f:
        return json.load(f)


def _build_slide_audio_map(manifest: Dict[str, Any], audio_dir: Path) -> Dict[int, Path]:
    slide_audio_map: Dict[int, Path] = {}
    for entry in manifest.get("slides", []):
        audio_file = entry.get("audio_file")
        if not audio_file:
            continue
        slide_num = int(entry["slide_num"])
        slide_audio_map[slide_num] = audio_dir / audio_file
    return slide_audio_map


def insert_audio(
    pptx_path: Path | str,
    manifest: Dict[str, Any],
    audio_dir: Path | str,
    output_path: Optional[Path | str] = None,
    visible: bool = True,
    powerpoint_app: Optional[Any] = None,
    progress_callback: Optional[Callable[[int, int, int, str], None]] = None,
) -> Dict[str, Any]:
    """Insert each slide's audio file into its matching slide.

    Args:
        pptx_path: Path to the source .pptx file.
        manifest: The audio manifest dict (as produced by
            ``tts.generate_audio_files`` / saved as manifest.json), mapping
            slide numbers to audio file names.
        audio_dir: Directory containing the MP3 files referenced by the
            manifest (the manifest only stores file names, not full paths).
        output_path: Where to save the resulting .pptx. Defaults to
            overwriting ``pptx_path``.
        visible: Whether the PowerPoint window should be shown while working.
            PowerPoint's COM automation is more reliable with the window
            visible; kept as a parameter so it can be hidden once the flow
            is proven stable.
        powerpoint_app: Optional pre-existing PowerPoint COM Application
            object. Mainly used for testing (inject a fake) or to reuse an
            already-running instance instead of starting a new one.
        progress_callback: Optional callback invoked as
            ``progress_callback(current, total, slide_num, status)`` right
            after each slide referenced by the manifest is processed -
            ``current`` is 1-based, ``total`` is how many slides the
            manifest references, and ``status`` is either ``"inserted"`` or
            ``"skipped"``. Slides can take a while to process one at a time
            over COM, so this is worth surfacing instead of leaving the
            caller waiting with no feedback until the whole deck is done.

    Returns:
        A summary dict: ``{"output_path", "inserted_slides", "skipped_slides"}``.

    Slides without a matching audio file are left untouched entirely -
    no shapes are added and no slide settings are changed. Per-slide
    problems (missing audio file, bad slide number, failed insertion) are
    recorded in ``skipped_slides`` rather than raised, so one bad slide
    doesn't abort the whole deck.

    Raises:
        PowerPointLaunchError: if PowerPoint can't be started or the
            presentation can't be opened.
        AudioInsertionError: if the resulting .pptx can't be saved.
        FileNotFoundError: if ``pptx_path`` doesn't exist.
    """
    _require_windows()

    pptx_path = Path(pptx_path).resolve()
    audio_dir = Path(audio_dir).resolve()
    output_path = Path(output_path).resolve() if output_path else pptx_path

    if not pptx_path.exists():
        raise FileNotFoundError(f"PPTX file not found: {pptx_path}")

    slide_audio_map = _build_slide_audio_map(manifest, audio_dir)
    total = len(slide_audio_map)

    with _powerpoint_session(powerpoint_app, visible) as (app, _created_app):
        with _open_presentation(app, pptx_path, visible) as presentation:
            inserted: List[int] = []
            skipped: List[Dict[str, Any]] = []

            # Compute a top-right position for the (shrunk) audio icon so it
            # stays out of the way of slide content, without moving it off
            # the visible slide area (the deck may be reused/edited
            # standalone).
            slide_width = presentation.PageSetup.SlideWidth
            icon_left = slide_width - ICON_SIZE_PT - ICON_MARGIN_PT
            icon_top = ICON_MARGIN_PT

            for index, (slide_num, audio_path) in enumerate(slide_audio_map.items(), start=1):
                if not audio_path.exists():
                    skipped.append(
                        {"slide_num": slide_num, "reason": f"audio file not found: {audio_path}"}
                    )
                    if progress_callback is not None:
                        progress_callback(index, total, slide_num, "skipped")
                    continue

                try:
                    slide = presentation.Slides(slide_num)
                except Exception as exc:  # noqa: BLE001 - surface as a skip, not a crash
                    skipped.append({"slide_num": slide_num, "reason": f"slide not found: {exc}"})
                    if progress_callback is not None:
                        progress_callback(index, total, slide_num, "skipped")
                    continue

                try:
                    shape = slide.Shapes.AddMediaObject2(
                        FileName=str(audio_path),
                        LinkToFile=False,
                        SaveWithDocument=True,
                        Left=icon_left,
                        Top=icon_top,
                        Width=ICON_SIZE_PT,
                        Height=ICON_SIZE_PT,
                    )
                except Exception as exc:  # noqa: BLE001
                    skipped.append(
                        {"slide_num": slide_num, "reason": f"failed to insert audio: {exc}"}
                    )
                    if progress_callback is not None:
                        progress_callback(index, total, slide_num, "skipped")
                    continue

                # Best-effort: hide the icon except while it's actually
                # playing, and mark it to play on entry. NOTE: empirically,
                # PlayOnEntry is NOT just cosmetic - even though it doesn't
                # change what the editor UI shows (still "On Click"), leaving
                # it unset caused PowerPoint's "Create a Video" export to
                # ignore the audio entirely and fall back to a fixed
                # 5-second slide duration with no sound. Keep both flags set
                # together.
                try:
                    shape.AnimationSettings.PlaySettings.PlayOnEntry = True
                    shape.AnimationSettings.PlaySettings.HideWhileNotPlaying = True
                except Exception:  # noqa: BLE001
                    pass

                inserted.append(slide_num)
                if progress_callback is not None:
                    progress_callback(index, total, slide_num, "inserted")

            try:
                presentation.SaveAs(str(output_path))
            except Exception as exc:
                raise AudioInsertionError(
                    f"Failed to save PPTX with inserted audio to {output_path}: {exc}"
                ) from exc

            return {
                "output_path": str(output_path),
                "inserted_slides": inserted,
                "skipped_slides": skipped,
            }


# PpMediaTaskStatus enumeration (Microsoft PowerPoint COM/VBA reference).
# Used to interpret Presentation.CreateVideoStatus while polling.
PP_MEDIA_TASK_STATUS_NONE = 0
PP_MEDIA_TASK_STATUS_IN_PROGRESS = 1
PP_MEDIA_TASK_STATUS_QUEUED = 2
PP_MEDIA_TASK_STATUS_DONE = 3
PP_MEDIA_TASK_STATUS_FAILED = 4

_STATUS_NAMES = {
    PP_MEDIA_TASK_STATUS_NONE: "none",
    PP_MEDIA_TASK_STATUS_IN_PROGRESS: "in_progress",
    PP_MEDIA_TASK_STATUS_QUEUED: "queued",
    PP_MEDIA_TASK_STATUS_DONE: "done",
    PP_MEDIA_TASK_STATUS_FAILED: "failed",
}


def export_video(
    pptx_path: Path | str,
    output_path: Path | str,
    resolution_height: int = 720,
    frames_per_second: int = 30,
    quality: int = 85,
    default_slide_duration: float = 5.0,
    use_timings_and_narrations: bool = False,
    timeout_seconds: float = 3600,
    poll_interval_seconds: float = 2.0,
    visible: bool = True,
    powerpoint_app: Optional[Any] = None,
    progress_callback: Optional[Callable[[str], None]] = None,
) -> Dict[str, Any]:
    """Export a .pptx to .mp4 using PowerPoint's "Create a Video" feature.

    This mirrors the export dialog PowerPoint itself shows: resolution
    (``resolution_height`` = the vertical pixel count PowerPoint's presets
    use, e.g. 720 for "HD (720p)", 1080 for "Full HD (1080p)"),
    "use recorded timings and narrations", and "seconds spent on each
    slide" (the fallback duration for slides with neither recorded timing
    nor auto-playing media - see ``insert_audio``'s notes on ``PlayOnEntry``
    for why slides with inserted audio ignore this fallback and use the
    audio's own length instead).

    ``Presentation.CreateVideo()`` is asynchronous: calling it only starts
    the export in PowerPoint's background thread. This function polls
    ``Presentation.CreateVideoStatus`` until it reports done or failed, or
    until ``timeout_seconds`` elapses.

    Args:
        pptx_path: Path to the .pptx to export (typically the output of
            ``insert_audio``, i.e. the deck that already has audio embedded).
        output_path: Where to write the resulting .mp4.
        resolution_height: Vertical resolution in pixels. Width is derived
            automatically by PowerPoint from the slide's aspect ratio.
        frames_per_second: Video frame rate.
        quality: Encoding quality, 0-100 (PowerPoint's own default is 85).
        default_slide_duration: Seconds to show a slide that has neither
            recorded timing nor auto-playing media (e.g. a cover slide with
            no inserted audio). Matches the "Seconds spent on each slide"
            field in PowerPoint's export dialog.
        use_timings_and_narrations: Whether to use recorded slide timings /
            narrations instead of ``default_slide_duration`` /
            embedded-audio-driven timing. Defaults to False to match
            PowerPoint's "Don't Use Recorded Timings and Narrations" option,
            which is what this project's decks use (timing comes from
            embedded audio, not recorded rehearsal timings).
        timeout_seconds: Give up waiting after this many seconds and raise
            ``VideoExportTimeoutError``. Export time scales with slide count
            and resolution; the default (3600s / 1hr) may need to be raised
            for long decks.
        poll_interval_seconds: How often to check ``CreateVideoStatus``.
        visible: Whether the PowerPoint window should be shown while working.
        powerpoint_app: Optional pre-existing PowerPoint COM Application
            object. Mainly used for testing (inject a fake) or to reuse an
            already-running instance instead of starting a new one.
        progress_callback: Optional callback invoked as
            ``progress_callback(status_name)`` (e.g. ``"in_progress"``,
            ``"queued"``) whenever the polled status changes.

    Returns:
        A summary dict: ``{"output_path", "elapsed_seconds"}``.

    Raises:
        PowerPointLaunchError: if PowerPoint can't be started or the
            presentation can't be opened.
        VideoExportError: if PowerPoint reports the export failed
            (``CreateVideoStatus`` == failed), or if the output file is
            missing/empty after a reported "done" status (a safety net in
            case the status enum values behave differently than documented
            on a given PowerPoint version).
        VideoExportTimeoutError: if the export does not finish within
            ``timeout_seconds``. Also catchable as ``TimeoutError``.
        FileNotFoundError: if ``pptx_path`` doesn't exist.
    """
    _require_windows()

    pptx_path = Path(pptx_path).resolve()
    output_path = Path(output_path).resolve()
    output_path.parent.mkdir(parents=True, exist_ok=True)

    if not pptx_path.exists():
        raise FileNotFoundError(f"PPTX file not found: {pptx_path}")

    with _powerpoint_session(powerpoint_app, visible) as (app, _created_app):
        with _open_presentation(app, pptx_path, visible) as presentation:
            presentation.CreateVideo(
                FileName=str(output_path),
                UseTimingsAndNarrations=use_timings_and_narrations,
                DefaultSlideDuration=default_slide_duration,
                VertResolution=resolution_height,
                FramesPerSecond=frames_per_second,
                Quality=quality,
            )

            start_time = time.monotonic()
            last_status = None

            while True:
                status = presentation.CreateVideoStatus
                status_name = _STATUS_NAMES.get(status, f"unknown({status})")

                if progress_callback is not None and status != last_status:
                    progress_callback(status_name)
                    last_status = status

                if status == PP_MEDIA_TASK_STATUS_DONE:
                    break
                if status == PP_MEDIA_TASK_STATUS_FAILED:
                    raise VideoExportError(
                        "PowerPoint reported the video export failed "
                        "(CreateVideoStatus = failed)."
                    )

                elapsed = time.monotonic() - start_time
                if elapsed > timeout_seconds:
                    raise VideoExportTimeoutError(
                        f"Timed out after {timeout_seconds}s waiting for PowerPoint "
                        f"to finish exporting {output_path.name} "
                        f"(last status: {status_name})."
                    )

                time.sleep(poll_interval_seconds)

            # Safety net: don't just trust the reported "done" status (the
            # status enum's exact numeric values are documented but
            # unverified against every PowerPoint COM version in practice) -
            # confirm the output file actually exists and isn't empty before
            # declaring success.
            if not output_path.exists() or output_path.stat().st_size == 0:
                raise VideoExportError(
                    "PowerPoint reported the video export as done, but no "
                    f"non-empty output file was found at {output_path}."
                )

            return {
                "output_path": str(output_path),
                "elapsed_seconds": time.monotonic() - start_time,
            }
